INSERT INTO "Equipment" (
  "id", 
  "name", 
  "category", 
  "location", 
  "description", 
  "price", 
  "image",
  "createdAt",
  "updatedAt"
) VALUES
('1', 'Canon EOS R5', 'Cameras', 'Vijayawada, AP', 'High-resolution mirrorless camera with 8K video capability.', 'Rs.2000/day', '/img/eq1.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('2', 'Green Screen Backdrop Kit', 'Backdrops', 'Banglore, Karnataka', 'Complete kit for green screen shoots.', 'Rs.700/day', '/img/eq25.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('3', 'Proaim DSLR Dolly', 'Dollies', 'Berlin, Germany', 'Lightweight dolly for DSLR cameras.', 'Rs.800/day', '/img/eq23.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('4', 'GVM Motorized Slider', 'Dollies', 'Hyderabad, Telangana', 'Motorized slider for smooth tracking shots.', 'Rs.650/day', '/img/eq24.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('5', 'Lexar Professional 256GB', 'Memory Cards', 'Hyderabad, Telangana', 'Ultra-fast CFexpress card, ideal for raw video.', 'Rs.250/day', '/img/eq18.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('6', 'PolarPro Peter McKinnon ND Filter', 'Filters', 'Vijayawada, AP', 'Premium ND filter for cinematic shots.', 'Rs.450/day', '/img/eq22.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('7', 'Glidecam HD-4000', 'Stabilizers', 'Vijayawada, AP', 'Handheld stabilizer for smooth shots.', 'Rs.500/day', '/img/eq19.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('8', 'Steadicam Zephyr', 'Stabilizers', 'Banglore, Karnataka', 'Professional stabilizer for dynamic shots.', 'Rs.700/day', '/img/eq20.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('9', 'SanDisk Extreme Pro 128GB', 'Memory Cards', 'Hyderabad, Telangana', 'High-speed SD card for 4K recording.', 'Rs.200/day', '/img/eq17.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('10', 'Atomos Ninja V', 'Monitors', 'Banglore, Karnataka', 'Portable 4K HDMI recorder with a bright 5-inch display.', 'Rs.1000/day', '/img/eq15.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('11', 'Manfrotto MVH502AH', 'Tripods', 'Hyderabad, Telangana', 'Video tripod with fluid head for smooth panning.', 'Rs.500/day', '/img/eq13.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('12', 'Tiffen Variable ND Filter', 'Filters', 'Banglore, Karnataka', 'Adjustable ND filter, 2-8 stops.', 'Rs.400/day', '/img/eq21.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('13', 'White Muslin Backdrop', 'Backdrops', 'Mumbai, India', 'Perfect for product and portrait shoots.', 'Rs.400/day', '/img/eq26.avif', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('14', 'Peak Design Travel Tripod', 'Tripods', 'Hyderabad, Telangana', 'Lightweight and sturdy, perfect for on-the-go shoots.', 'Rs.600/day', '/img/eq14.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('15', 'DJI Mavic Air 2', 'Drones', 'Mumbai, Maharashtra', 'Compact drone with high-quality 4K video.', 'Rs.2000/day', '/img/eq12.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('16', 'Sony A7S III', 'Cameras', 'Hyderabad, Telangana', 'Ideal for low-light shooting, 4K up to 120fps.', 'Rs.1700/day', '/img/eq2.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('17', 'Canon EF 50mm f/1.2L', 'Lenses', 'Hyderabad, Telangana', 'Prime lens, excellent for portrait and low-light shots.', 'Rs.600/day', '/img/eq3.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('18', 'Sigma 24-70mm f/2.8 DG DN', 'Lenses', 'Guntur, AP', 'Versatile zoom lens, ideal for various shooting styles.', 'Rs.950/day', '/img/eq4.jpeg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('19', 'Aputure 120D II', 'Lighting Equipment', 'Mumbai, Maharashtra', 'Powerful LED light, ideal for both indoor and outdoor shoots.', 'Rs.1000/day', '/img/eq5.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('20', 'Godox SL-60W', 'Lighting Equipment', 'Vijayawada, AP', 'Affordable LED light with adjustable brightness.', 'Rs.750/day', '/img/eq6.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('21', 'DJI Ronin-S', 'Gimbals', 'Hyderabad, Telangana', 'Stabilizer for smooth and dynamic shots.', 'Rs.600/day', '/img/eq7.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('22', 'Zhiyun Crane 3S', 'Gimbals', 'Mumbai, India', 'Heavy-duty gimbal for larger cameras.', 'Rs.500/day', '/img/eq8.webp', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('23', 'Rode NTG4+ Shotgun Mic', 'Audio Equipment', 'Banglore, Karnataka', 'Directional mic, ideal for capturing clear dialogue.', 'Rs.350/day', '/img/eq9.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('24', 'Zoom H5 Handy Recorder', 'Audio Equipment', 'Hyderabad, Telangana', 'Portable audio recorder with X/Y microphone capsule.', 'Rs.750/day', '/img/eq10.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('25', 'SmallHD 702 Bright', 'Monitors', 'Vijayawada, AP', '7-inch daylight-viewable monitor.', 'Rs.500/day', '/img/eq16.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
