INSERT INTO "People" (id, name, location, description, role, image, "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'Ravi Desai', 'Ahmedabad, India', 'Video editor with a knack for pacing and compelling narrative flow.', 'Editor', '/img/headshot23.avif', NOW(), NOW()),
  (gen_random_uuid(), 'Arya Patel', 'Mumbai, India', 'Experienced actor with a range from drama to comedy, known for captivating performances.', 'Actor', '/img/headshot1.png', NOW(), NOW()),
  (gen_random_uuid(), 'Bruno', 'Berlin, Germany', 'Barks well', 'Actor', '/img/headshot11.webp', NOW(), NOW()),
  (gen_random_uuid(), 'Sofia Lopez', 'Mexico City, Mexico', 'Screenwriter with a flair for creating intense dramas and inspiring love stories.', 'Writer', '/img/headshot2.avif', NOW(), NOW()),
  (gen_random_uuid(), 'Manoj Pillai', 'Trivandrum, India', 'Experienced producer with a portfolio of successful regional films.', 'Producer', '/img/headshot29.webp', NOW(), NOW()),
  (gen_random_uuid(), 'Ryo Takahashi', 'Tokyo, Japan', 'Award-winning director known for stunning visuals and deep storytelling in independent films.', 'Director', '/img/headshot2.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Lena Chen', 'Shanghai, China', 'Animator with a vibrant style, bringing unique character animations to life in 2D and 3D.', 'Animator', '/img/headshot3.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Jamal Roberts', 'New York, USA', 'Talented cinematographer capturing beautiful, dramatic shots across diverse landscapes.', 'Cinematographer', '/img/headshot4.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Amara Singh', 'Toronto, Canada', 'Accomplished producer with experience in managing large-scale film projects globally.', 'Producer', '/img/headshot5.jpeg', NOW(), NOW()),
  (gen_random_uuid(), 'David Miller', 'Los Angeles, USA', 'Expert video editor specializing in storytelling and seamless transitions for high-impact videos.', 'Editor', '/img/headshot6.jpeg', NOW(), NOW()),
  (gen_random_uuid(), 'Emily Wong', 'Hong Kong, China', 'Versatile actress with experience in both theatre and film, bringing characters to life.', 'Actor', '/img/headshot7.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Javier Garcia', 'Madrid, Spain', 'Talented writer specializing in sci-fi and fantasy scripts for films and series.', 'Writer', '/img/headshot8.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Isabella Marini', 'Rome, Italy', 'Director focused on creating powerful, character-driven stories in drama films.', 'Director', '/img/headshot9.avif', NOW(), NOW()),
  (gen_random_uuid(), 'Priya Desai', 'Bangalore, India', 'Creative animator specializing in motion graphics and visual storytelling.', 'Animator', '/img/headshot10.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Julia Evans', 'London, UK', 'Producer experienced in both independent films and big-budget productions.', 'Producer', '/img/headshot12.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Yuki Yamamoto', 'Osaka, Japan', 'Director creating emotionally impactful indie films.', 'Director', '/img/headshot16.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Karan Singh', 'Mumbai, India', 'Dynamic actor with experience in Bollywood films and stage performances.', 'Actor', '/img/headshot17.webp', NOW(), NOW()),
  (gen_random_uuid(), 'Anjali Mehta', 'Pune, India', 'Writer specializing in romance and family dramas for Indian cinema.', 'Writer', '/img/headshot18.png', NOW(), NOW()),
  (gen_random_uuid(), 'Vikram Reddy', 'Hyderabad, India', 'Director known for gritty crime thrillers and intense storytelling.', 'Director', '/img/headshot19.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Priyanka Sharma', 'Kolkata, India', 'Cinematographer capturing vibrant visuals and dramatic compositions.', 'Cinematographer', '/img/headshot20.webp', NOW(), NOW()),
  (gen_random_uuid(), 'Siddharth Nair', 'Chennai, India', 'Producer with experience in both commercial and independent film projects.', 'Producer', '/img/headshot21.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Lakshmi Menon', 'Bangalore, India', 'Talented animator creating expressive character animations in 2D and 3D.', 'Animator', '/img/headshot22.jpeg', NOW(), NOW()),
  (gen_random_uuid(), 'Neha Kapoor', 'Jaipur, India', 'Actress with a background in theatre and Bollywood, known for her emotional range.', 'Actor', '/img/headshot24.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Rahul Jain', 'Surat, India', 'Writer skilled in action-packed scripts and witty dialogue.', 'Writer', '/img/headshot25.webp', NOW(), NOW()),
  (gen_random_uuid(), 'Amrita Das', 'Lucknow, India', 'Director focusing on character-driven dramas and thought-provoking stories.', 'Director', '/img/headshot26.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Rajiv Patel', 'Nagpur, India', 'Cinematographer with an eye for natural lighting and breathtaking visuals.', 'Cinematographer', '/img/headshot27.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Tommy Chen', 'Vancouver, Canada', 'Video editor known for precise cuts and impactful storytelling.', 'Editor', '/img/headshot13_1.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Marie Dubois', 'Paris, France', 'Actress with a background in theatre, known for her expressive performances.', 'Actor', '/img/headshot14.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Alex Knight', 'Los Angeles, USA', 'Experienced writer with a knack for horror and thriller scripts.', 'Writer', '/img/headshot15.webp', NOW(), NOW()),
  (gen_random_uuid(), 'Ananya Iyer', 'Coimbatore, India', 'Animator bringing unique character animations to life in animated short films.', 'Animator', '/img/headshot28.jpg', NOW(), NOW()),
  (gen_random_uuid(), 'Rita Gupta', 'Patna, India', 'Video editor specializing in documentaries and non-linear storytelling.', 'Editor', '/img/heashot30.jpg', NOW(), NOW());
